added function url resource to module
bankrate/terraform-aws-lambda pull request #7
Opened 2022-07-14 20:49 UTC by Halima-RV

2022-07-15 16:21 UTC, rv-jgentile commented on examples/example-with-functionurl/main.tf
> +}
Mind running a quick `terraform format` on this dir real quick just to line these operators up?

2022-07-15 16:21 UTC, rv-jgentile commented on variables.tf
> +}
`terraform fmt` on this dir as well pls

2022-07-15 16:25 UTC, rv-jgentile commented
Let's include `aws_lambda_function_url` in the outputs here. Might take a bit of trickery since it may or may not be created, but it can probably be addressed with a ternary that does (pseudo-code incoming):
```
value = enable_functionurl ? aws_lambda_function_url : ""
```
shouldn't take too much tinkering to get it working

2022-07-15 16:41 UTC, Halima-RV commented on variables.tf
> +}
Done, Thank you

2022-07-15 17:32 UTC, rv-jgentile approved these changes, later dismissed

2022-07-15 17:56 UTC, lbrimeyer commented
> Let's include `aws_lambda_function_url` in the outputs here. Might take a bit of trickery since it may or may not be created, but it can probably be addressed with a ternary that does (pseudo-code incoming):
> 
> ```
> value = enable_functionurl ? aws_lambda_function_url : ""
> ```
> 
> shouldn't take too much tinkering to get it working
> 
> _Edit: Just realized I should probably include reasoning, lol._
> 
> Outputting the url will make it a lot easier for users. If they want a function url then they're gonna want to use it _somewhere_. Adding it to outputs makes it obvious what url was created. Without that output they'd probably have to go digging around the console to figure out what endpoint they have to plug into their app/browser/etc. Might as well just throw it up on the screen.

```
value = enable_functionurl ? aws_lambda_function_url : null
```
This would be my preference if it works to avoid outputting anything if it's disabled. 
Worth noting in a ton of languages (ideally one day including HCL/GoLang) null != undefined != empty/zero-value and the difference in those meanings is usually important.

2022-07-15 17:58 UTC, lbrimeyer commented on main.tf
> +  count              = var.enable_functionurl ? 1 : 0
```suggestion
  count              = var.enable && lookup(var.architecture, "function_url", false) ? 1 : 0
```
This follow the architecture pattern we've established for the other event sources and lambda triggers.

2022-07-15 17:59 UTC, lbrimeyer commented on variables.tf
>    }
I'd add function_url to this struct.

2022-07-15 18:01 UTC, lbrimeyer requested changes
Minor structure change for architecture to include function_url instead of an entirely new variable and how the output is handled.

2022-07-25 21:51 UTC, lbrimeyer requested changes
Adding the variable for auth type but otherwise this looks slick!

2022-07-25 21:51 UTC, lbrimeyer commented on main.tf
> +  authorization_type = "AWS_IAM"
Let's swap this to a variable that validates whether either `AWS_IAM` or `NONE`,  default to `AWS_IAM` as the default (more secure) option out of the gate. Great points during Zoom PR 🏅 .

2022-07-26 19:18 UTC, lbrimeyer requested changes
Super super close 🏅

2022-07-26 19:18 UTC, lbrimeyer commented on variables.tf
> +  default = "AWS_IAM"
```suggestion
  default = "AWS_IAM"
  
  validation {
    condition           = contains(["AWS_IAM", "NONE"], var.authorization_type)
    error_message = "Authorization type must be either `AWS_IAM` || `NONE`"
  }
```

2022-07-26 19:25 UTC, lbrimeyer approved these changes

2022-07-26 19:32 UTC, rv-jgentile approved these changes

2022-07-26 19:33 UTC, merged